name: compass
description: "An unofficial companion app for DoTa 2."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.0.0
  control_style: ^0.1.0
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  graphql: ^5.2.0
  html: ^0.15.5+1
  html_unescape: ^2.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - lib/icons/
    - lib/images/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/fonts/Inter.ttf

icons_launcher:
  image_path: "lib/images/compass-logo.png"
  platforms:
    android:
      enable: true
      adaptive_foreground_image: "lib/images/compass-logo.png"
    ios:
      enable: true

flutter_native_splash:
  color: "#1a1a1a"
  image: "lib/images/compass-logo.png"

  android_12:
    image: "lib/images/compass-logo.png"
    icon_background_color: "#1a1a1a"
